import { ethers } from 'ethers';

/**
 * Blockchain provider and signer utilities for Carbon Bazaar.
 *
 * Reads configuration from environment variables:
 * - POLYGON_RPC_URL: RPC endpoint (Alchemy/Infura/public)
 * - SERVER_WALLET_PRIVATE_KEY: Deployer/operator wallet private key
 * - CARBON_CONTRACT_ADDRESS: Deployed CarbonCreditBatch contract address
 *
 * The server wallet is the contract owner and can:
 * - Mint new carbon credit batches
 * - Transfer credits on behalf of users (as approved operator)
 * - Retire credits on behalf of users (as approved operator)
 */

let _provider = null;
let _serverSigner = null;
let _contractData = null;

/**
 * Get a read-only JSON-RPC provider.
 */
export function getProvider() {
  if (!_provider) {
    const rpcUrl = process.env.POLYGON_RPC_URL || 'http://127.0.0.1:8545';
    const isLocal = rpcUrl.includes('127.0.0.1') || rpcUrl.includes('localhost');
    const staticNet = isLocal
      ? ethers.Network.from({ chainId: 31337, name: 'hardhat' })
      : ethers.Network.from({ chainId: 80002, name: 'polygon-amoy' });

    _provider = new ethers.JsonRpcProvider(rpcUrl, staticNet, { staticNetwork: staticNet });
  }
  return _provider;
}

/**
 * Get the server's signer (for executing transactions).
 */
export function getServerSigner() {
  if (!_serverSigner) {
    const privateKey = process.env.SERVER_WALLET_PRIVATE_KEY;
    if (!privateKey) {
      throw new Error('SERVER_WALLET_PRIVATE_KEY environment variable is not set');
    }
    _serverSigner = new ethers.Wallet(privateKey, getProvider());
  }
  return _serverSigner;
}

/**
 * Load the contract ABI and address from the deployed contract data.
 * This file is generated by the deploy script.
 */
async function getContractData() {
  if (!_contractData) {
    const envAddress = process.env.CARBON_CONTRACT_ADDRESS;
    try {
      const data = await import('./contract.json');
      const loaded = data.default || data;
      _contractData = {
        address: (envAddress && envAddress !== '0x0000000000000000000000000000000000000000') ? envAddress : loaded.address,
        abi: loaded.abi || getMinimalABI(),
      };
    } catch {
      if (!envAddress) {
        throw new Error(
          'Contract data not found. Either deploy the contract first (which generates contract.json) ' +
          'or set CARBON_CONTRACT_ADDRESS in environment variables.'
        );
      }
      _contractData = {
        address: envAddress,
        abi: getMinimalABI(),
      };
    }
  }
  return _contractData;
}

/**
 * Get an ethers Contract instance connected to the server signer.
 */
export async function getContract() {
  const { address, abi } = await getContractData();
  const signer = getServerSigner();
  return new ethers.Contract(address, abi, signer);
}

/**
 * Get a read-only contract instance (no signer needed).
 */
export async function getReadOnlyContract() {
  const { address, abi } = await getContractData();
  const provider = getProvider();
  return new ethers.Contract(address, abi, provider);
}

/**
 * Get the deployed contract address.
 */
export async function getContractAddress() {
  const { address } = await getContractData();
  return address;
}

/**
 * Minimal ABI covering only the functions Carbon Bazaar uses.
 * Used as a fallback when contract.json is not available.
 */
function getMinimalABI() {
  return [
    'function mintBatch(address issuer, uint256 amount, string projectHash, string metadataURI) external returns (uint256)',
    'function transferCredits(address from, address to, uint256 tokenId, uint256 amount) external',
    'function retireCredits(address holder, uint256 tokenId, uint256 amount) external',
    'function getBatchInfo(uint256 tokenId) external view returns (address issuer, uint256 totalSupply, uint256 totalRetired, uint256 activeSupply, string projectHash, string metadataURI, uint256 mintedAt)',
    'function balanceOf(address account, uint256 id) external view returns (uint256)',
    'function getRetiredAmount(uint256 tokenId, address holder) external view returns (uint256)',
    'function nextTokenId() external view returns (uint256)',
    'function setApprovalForAll(address operator, bool approved) external',
    'function isApprovedForAll(address account, address operator) external view returns (bool)',
    'event BatchMinted(uint256 indexed tokenId, address indexed issuer, uint256 amount, string projectHash, string metadataURI)',
    'event CreditsTransferred(uint256 indexed tokenId, address indexed from, address indexed to, uint256 amount)',
    'event CreditsRetired(uint256 indexed tokenId, address indexed holder, uint256 amount, uint256 timestamp)',
  ];
}
